<div style="overflow:auto;">
<table class="table table-bordered hos_table1" >
	<thead>
		<tr>
			<th>出生队列编号no2</th>
			<th>母亲姓名</th>
			<th>母亲编号</th>
			<th>身份证号</th>
			<th>母亲生日</th>
			<th>末次月经</th>
			<th>分娩日期</th>
			<th>胎数</th>
			<th>新生儿性别</th>
			<th>分娩方式</th>
			<th>分娩孕周</th>
			<th>分娩孕周--周</th>
			<th>分娩孕周--周分组</th>
			<th>分娩孕周--天</th>
			<th>孕妇电话</th>
			<th>丈夫电话</th>
			<th>备用电话</th>
			<th>孕晚期血清</th>
			<th>孕晚期血浆</th>
			<th>孕晚期血细胞</th>
			<th>脐血清</th>
			<th>脐血浆</th>
			<th>脐血细胞</th>
			<th>胎盘</th>
			<th>孕晚期尿液</th>
			<th>孕晚期尿液袋号</th>
			<th>孕晚期尿液导尿</th>
			<th>儿童姓名</th>
			<th>丈夫姓名</th>
			<th>年龄岁</th>
			<th>城镇乡村</th>
			<th>计划外引产</th>
			<th>会阴破裂</th>
			<th>会阴切开</th>
			<th>会阴缝合</th>
			<th>产后2小时宫缩</th>
			<th>出血量ml</th>
			<th>孕产妇HIV筛查</th>
			<th>出院前母乳喂养</th>
			<th>院外分娩</th>
			<th>产后出血ml</th>
			<th>产妇死亡</th>
			<th>孕妇死亡</th>
			<th>存活情况</th>
			<th>健康状况</th>
			<th>出生体重g</th>
			<th>出生身长cm</th>
			<th>出生头围cm</th>
			<th>分娩时间时</th>
			<th>分娩时间分</th>
			<th>胎方位</th>
			<th>产程一</th>
			<th>第一产程时</th>
			<th>第一产程分</th>
			<th>第一产程时间（min）</th>
			<th>产程二</th>
			<th>第二产程时</th>
			<th>第二产程分</th>
			<th>第二产程时间（min）</th>
			<th>产程三</th>
			<th>第三产程时</th>
			<th>第三产程分</th>
			<th>第三产程时间（min）</th>
			<th>总产程</th>
			<th>总产程时</th>
			<th>总产程分</th>
			<th>总产程时间（min）</th>
			<th>早吸吮</th>
			<th>阿氏评分1分钟</th>
			<th>阿氏评分5分钟</th>
			<th>破伤风</th>
			<th>新生儿筛查</th>
			<th>听力筛查</th>
			<th>听力筛查复查</th>
			<th>新生儿出生体重百分位数--90%（基于新生儿性别）</th>
			<th>新生儿出生体重百分位数--10%（基于新生儿性别）</th>
			<th>低出生体重</th>
			<th>巨大儿</th>
			<th>早产</th>
			<th>小于胎龄儿</th>
			<th>大于胎龄儿</th>
			<th>Q00-Q99新生儿畸形--新生儿畸形</th>
			<th>O10原有的高血压并发于妊娠、分娩和产褥期--妊娠合并慢性高血压</th>
			<th>O11慢性高血压合并子痫前期--原发性高血压合并子痫</th>
			<th>O11慢性高血压合并子痫前期--原发性高血压合并子痫前期</th>
			<th>O12妊娠期水肿和蛋白尿--妊娠合并蛋白尿</th>
			<th>O13妊娠期高血压--妊娠期高血压</th>
			<th>O14.2HELLP综合征--HELLP综合征</th>
			<th>O14子痫前期--子痫前期</th>
			<th>O14子痫前期--轻度子痫前期</th>
			<th>O14子痫前期--重度子痫前期</th>
			<th>O14子痫前期--重度子痫</th>
			<th>O24妊娠期糖尿病--妊娠期糖耐量异常</th>
			<th>O24妊娠期糖尿病--妊娠期糖尿病</th>
			<th>O24妊娠期糖尿病--糖尿病</th>
			<th>O24妊娠期糖尿病--酮症酸中毒</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<th>no2</th>
			<th>name</th>
			<th>pid</th>
			<th>m_id</th>
			<th>id2</th>
			<th>lmp</th>
			<th>dedate</th>
			<th>fetus</th>
			<th>gender</th>
			<th>delive</th>
			<th>ga</th>
			<th>gad</th>
			<th>gaw</th>
			<th>gawg</th>
			<th>pphone</th>
			<th>hphone</th>
			<th>dephone</th>
			<th>serumt3</th>
			<th>plasmat3</th>
			<th>bcellt3</th>
			<th>cbser</th>
			<th>cbpla</th>
			<th>cbbcl</th>
			<th>placent</th>
			<th>urinet3</th>
			<th>urinet3_bag</th>
			<th>urinet3_dao</th>
			<th>bname</th>
			<th>hname</th>
			<th>var7</th>
			<th>var9</th>
			<th>var12</th>
			<th>var41</th>
			<th>var42</th>
			<th>var43</th>
			<th>var44</th>
			<th>var45</th>
			<th>var50</th>
			<th>var51</th>
			<th>var52</th>
			<th>var53</th>
			<th>var54</th>
			<th>var55</th>
			<th>var56</th>
			<th>var58</th>
			<th>var59</th>
			<th>var60</th>
			<th>var78</th>
			<th>var61</th>
			<th>var62</th>
			<th>var64</th>
			<th>var65</th>
			<th>var65_h</th>
			<th>var65_m</th>
			<th>var65_min</th>
			<th>var66</th>
			<th>var66_h</th>
			<th>var66_m</th>
			<th>var66_min</th>
			<th>var67</th>
			<th>var67_h</th>
			<th>var67_m</th>
			<th>var67_min</th>
			<th>var68</th>
			<th>var68_h</th>
			<th>var68_m</th>
			<th>var68_min</th>
			<th>var69</th>
			<th>var70</th>
			<th>var71</th>
			<th>var74</th>
			<th>var75</th>
			<th>var76</th>
			<th>var76_a</th>
			<th>bw_p90gs</th>
			<th>bw_p10gs</th>
			<th>lbw</th>
			<th>macro</th>
			<th>preterm</th>
			<th>sga</th>
			<th>lga</th>
			<th>neobd_001</th>
			<th>matpih_001</th>
			<th>matpih_002</th>
			<th>matpih_003</th>
			<th>matpih_004</th>
			<th>matpih_005</th>
			<th>matpih_006</th>
			<th>matpih_007</th>
			<th>matpih_008</th>
			<th>matpih_009</th>
			<th>matpih_010</th>
			<th>matgdm_001</th>
			<th>matgdm_002</th>
			<th>matgdm_003</th>
			<th>matgdm_004</th>
		</tr>
		<tr>
			<td>HP70001</td>
			<td>张文</td>
			<td>100012120914043201</td>
			<td>420124198210294328</td>
			<td>10/29/1982</td>
			<td>12/15/2011</td>
			<td>9/14/2012</td>
			<td>单胎</td>
			<td>男</td>
			<td>自然产</td>
			<td>39+1</td>
			<td>274</td>
			<td>39.14</td>
			<td>39</td>
			<td>15007115080</td>
			<td>13971053365</td>
			<td>15007115080</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td></td>
			<td></td>
			<td></td>
			<td>江楠</td>
			<td>江兵</td>
			<td>29</td>
			<td>城镇</td>
			<td>0</td>
			<td>完整</td>
			<td>否</td>
			<td>无需缝合</td>
			<td></td>
			<td>200</td>
			<td>1</td>
			<td>1</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>存活</td>
			<td>良好</td>
			<td>3600</td>
			<td>53</td>
			<td></td>
			<td>4</td>
			<td>3</td>
			<td>枕左前</td>
			<td>02小时40分</td>
			<td>2</td>
			<td>40</td>
			<td>160</td>
			<td>00小时23分</td>
			<td>0</td>
			<td>23</td>
			<td>23</td>
			<td>00小时02分</td>
			<td>0</td>
			<td>2</td>
			<td>2</td>
			<td>03小时05分</td>
			<td>3</td>
			<td>5</td>
			<td>185</td>
			<td>1</td>
			<td>10</td>
			<td>10</td>
			<td>0</td>
			<td>1</td>
			<td>通过</td>
			<td></td>
			<td>3812.290748</td>
			<td>2934.661519</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
			<td>0</td>
		</tr>
	</tbody>
</table>    
</div>